name: aiglasses_bledebugtools
description: "AI-Glasses-BLEDebugTools - Universal Cross-Platform Bluetooth Debug Assistant for AI Glasses, TWS Earbuds & BLE Devices."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BLE
  flutter_blue_plus: ^1.32.0

  # State management
  provider: ^6.1.1

  # Storage
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # UI
  google_fonts: ^6.1.0
  dynamic_color: ^1.7.0

  # Utilities
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  csv: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/plugin_config/
    - assets/register_map/
    - assets/protocols/
